# Generated by Django 3.1 on 2020-08-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verloop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
